apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ssh-proxy.fullname" . }}
  labels:
    {{- include "ssh-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ toYaml .Values.proxy.config | b64enc | quote }}
  {{- with .Values.proxy.hostKey.privateKey }}
  ssh_host_key: {{ . | b64enc | quote }}
  {{- end }}
